/**
 * File automatically generated by TypescriptMapper
 * DO NOT EDIT
 */
export interface Person {
	name: string;
	age: number;
	hasChildren: boolean;
	tags: string[];
	emails: { [ index: string ]: string };
}
