version: 2
jobs:
  build:
    # directory where steps will run
    working_directory: ~/typescript-mapper
    docker:
      - image: daniloarcidiacono/ci-java-node:0.4.0

    steps:
      # check out source code to working directory
      - checkout

      # restore the saved cache after the first run or if `pom.xml` has changed
      - restore_cache:
          key: typescript-mapper-{{ checksum "pom.xml" }}

      # gets the project dependencies
      #
      # Add the verify goal (from see https://issues.apache.org/jira/browse/MDEP-516):
      #
      # "It can be solved by using mvn package dependency:go-offline which creates a reactor and will works as expected.
      #  But you can also use mvn compile dependency:go-offline but with the drawback that you can't do a mvn -o package
      #  cause all things which are done after the life cycle phase compile will not being downloaded.."
      #  For example if you do mvn package dependency:go-offline and afterwards you do mvn -o deploy your build will fail
      #  cause maven-install-plugin can't be found, cause it has not been solved...."
      - run: mvn verify dependency:go-offline

      # saves the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: typescript-mapper-{{ checksum "pom.xml" }}

      # Build
      - run: mvn clean package verify -Pdocs

      # Deploy
      - deploy:
          name: "Create GitHub release"
          command: |
            hub release create -a typescript-mapper-core/target/typescript-mapper-core-$CIRCLE_TAG-javadoc.jar -a typescript-mapper-maven-plugin/target/typescript-mapper-maven-plugin-$CIRCLE_TAG-javadoc.jar -F CHANGELOG_LATEST.md $CIRCLE_TAG

      # Upload test coverage
      - run: bash <(curl -s https://codecov.io/bash)

      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
      - store_test_results:
          path: typescript-mapper-core/target/surefire-reports

      # store the jar as an artifact
      - store_artifacts:
          path: typescript-mapper-core/target/typescript-mapper-core-{{ .Environment.CIRCLE_TAG }}.jar

      - store_artifacts:
          path: typescript-mapper-maven-plugin/target/typescript-mapper-maven-plugin-{{ .Environment.CIRCLE_TAG }}.jar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/


