/**
 * This file is automatically generated by TypescriptMapper.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
export interface DependencyDTO {
}

export interface ExpandingDTO<T> {
	other: ExpandingDTO<DependencyDTO>;
}
