package io.github.daniloarcidiacono.typescript.mapper.renderer;

import io.github.daniloarcidiacono.typescript.mapper.mapper.TypescriptMapped;
import io.github.daniloarcidiacono.typescript.template.TypescriptComments;
import io.github.daniloarcidiacono.typescript.template.TypescriptRenderable;

import java.util.Collection;

public interface TypescriptRenderer {
     TypescriptRenderable PREAMBLE = new TypescriptComments()
             .comment("File automatically generated by TypescriptMapper")
             .comment("DO NOT EDIT");

     void render(final Collection<TypescriptMapped> mapped);
}
