/**
 * This file is automatically generated by TypescriptMapper.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
export interface Person {
	// The name of the person.
	name: string;
	age: number;
	hasChildren: boolean;
	tags: string[];

	/**
	 * The emails of the person.
	 * Key is provider, value is email.
	 */
	emails: { [ index: string ]: string };
}
