/**
 * This file is automatically generated by TypescriptMapper.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */
export interface EnclosingDTO {
}

export interface EnclosingFirstDTO {
}

export interface EnclosingFirstNestedDTO {
}

export interface EnclosingFirstOtherDTO {
}

export interface EnclosingSecondDTO {
}
